name: request
description: "封装网络请求"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  pretty_dio_logger: ^1.4.0
  flutter_easyloading: ^3.0.5
  dio: ^5.7.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
  json_annotation: ^4.9.0
flutter:

  uses-material-design: true

